name: CI

on: pull_request

jobs:
  lint:
    name: Run linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6.6'
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.17.2'
      - name: Install bundler
        run: gem install bundler:2.1.4
      - name: Bundle install
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: flutter doctor
        run: flutter doctor -v
      - name: Run flutter analyze
        id: analyze
        run: flutter analyze > flutter_analyze_report.txt
      - name: Run Danger
        run: bundle exec danger --remove-previous-comments --no-ansi >> danger.md
        if: always()
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # - name: Notify to slack
      #   if: always()
      #   uses: rtCamp/action-slack-notify@v2.0.2
      #   env:
      #     SLACK_USERNAME: Danger
      #     SLACK_TITLE: Danger output
      #     SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      #     MSG_MINIMAL: true
      #     SLACK_MESSAGE: 'Test message'
